name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari
  workflow_dispatch: # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Fzz90
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#ff4b82&color_dots=#ffffff,#00bfff,#ff7b00,#ffd700,#ff4b82
            dist/github-snake.gif?palette=github-light&color_snake=#ff4b82&color_dots=#ffffff,#00bfff,#ff7b00,#ffd700,#ff4b82

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
